### ISSUE TITLE
Is there any plan for localization?

### ISSUE THREAD

**Issue by icyblade** [amki/ElitismHelper#12]
Is there any plan for localization? I'd like to provide zhCN and zhTW translations if possible.

**Comment by amki** [comment]
Localization isn't planned per-se the spell name is loaded through world of warcraft's api though so that should auto-customize itself to the language your client uses.

**Comment by icyblade** [comment]
But some parts like https://github.com/amki/ElitismHelper/blob/48f8d13f98bf15a720de5a43f41bd335ec05b186/ElitismHelper.lua#L228 is always English.

**Comment by amki** [comment]
Ah sure, is there a well known way to internationalize WoW add-ons? I've not cared about it before.

Am 18. Oktober 2018 04:29:39 MESZ schrieb Yuchao Dai <notifications@github.com>:
>But some parts like
>https://github.com/amki/ElitismHelper/blob/48f8d13f98bf15a720de5a43f41bd335ec05b186/ElitismHelper.lua#L228
>is always English. 
>
>-- 
>You are receiving this because you commented.
>Reply to this email directly or view it on GitHub:
>https://github.com/amki/ElitismHelper/issues/12#issuecomment-430853829

-- 
Everything not saved will be lost. - Nintendo Quit Screen Message

**Comment by icyblade** [comment]
What about [AceLocale](https://www.wowace.com/projects/ace3/pages/api/ace-locale-3-0)?

**Comment by chedz-dev** [comment]
Hi. If the pull request #49 of mine is accepted, I will develop a localization module so we can be elitists in our own language. When the localization module is implemented, I will need help from the community to translate the addon to diferent languages. I can only help with Spanish translation.

**Comment by amki** [comment]
This never really materialized (also because it was linked to a gui config window (which we don't need?). If there is still need for this feel free to reopen an issue
