### ISSUE TITLE
Grave Bolt should not be considered avoidable damage

### ISSUE THREAD

**Issue by ghost** [amki/ElitismHelper#17]
I've been testing the new update and I noticed Grave Bolt is now listed as avoidable damage.

I don't feel as if taking damage from this spell truly shows the same level of lack of paying attention that most other avoidable damage shows.

The most important reason is that in practice, most people won't be able to keep all Grave Bolts from going off by themselves. The mechanic is a group effort, and outside of a few classes, is unable to be dealt with alone. 

Another reason being that they randomly target any player in their line of sight, and a lot of times no level of skill can prevent being hit by it outside of a party members help.

Overall it feels like calling out Grave Bolts doesn't really mix with the idea behind the addon.

**Comment by amki** [comment]
I removed Grave Bolt in 7f49c1ee1bd1cd7745384a4932e243d934b9ae58
