### ISSUE TITLE
Any way to track Spiteful melee hits?

### ISSUE THREAD

**Issue by yekul** [amki/ElitismHelper#31]
As title says, would love an option to be able to track Spiteful affix via people being hit by it. Less important for tank, but just did first run and melee were being destroyed by it and would love a way to say 'hey this is causing a lot of pressure on the healer'. 

If you don't plan to add it to main branch, any help on how to add it manually? I can add other spells no problem, but not sure how to deal with melee hits.

**Comment by amki** [comment]
As spiteful has never been online in EU (where I play) I don't really know how spiteful works but if it's avoidable damage we'll add it for sure.

From the logs I've just looked up it seems like you have to take spiteful damage though? That would make it very difficult to tell when it is a fail and when it was necessary.

**Comment by amki** [comment]
This should work in 05a75ac1a86d2ba0f42a94ba46461db67f158405 but I have not tested it yet. If it works I'll make a release for it.

If you want you can beta test this with me and give some feedback, it's the biggest change I've made in quite a while.

**Comment by amki** [comment]
This is now released as tag https://github.com/amki/ElitismHelper/releases/tag/0.12.1release if you find any problems with it feel free to open a new issue! :)
