### ISSUE TITLE
[Not an Avoidable Damage] Dark Stride

### ISSUE THREAD

**Issue by lmonteco** [amki/ElitismHelper#35]
Dungeon - Spires of Ascension
Boss - Ventunax
Ability - **Dark Stride** is not an avoidable skill

**Comment by amki** [comment]
Hmm do we have the wrong ID for this? I think the goal is to add the little shadow orbs that emanate from it.

I'll try to do SoA to get a log of the orbs.

**Comment by lmonteco** [comment]
You got the little shadow orbs correctly (Dark Bolt), just Dark Stride is wrong.

**[324154] = 20,		-- Dark Stride (Venturax)**
[324141] = 20,      -- Dark Bolt (Ventunax)

sorry, i shouldv sent u this before to help u out

https://www.wowhead.com/spell=324154/dark-stride

> Moving with incredible speed, Ventunax appears behind a player and inflicts 2344 Physical damage every second for 20 sec.Additionally, Ventunax leaves a Shadowhirl behind.

The spell itself can't be avoidable. But what it left behind it, that is Shadowhirl (which launches Dark Bolts), can be.

--

**Comment by amki** [comment]
Thank you for the report it is fixed in the marked commit and I've released a new version.
