### ISSUE TITLE
self/observer output not working correctly

### ISSUE THREAD

**Issue by T3ll1nG** [amki/ElitismHelper#36]
Since about 2-3 versions ago self/observer output is broken. The addon works fine if you have it on default output but on observer the addon will not auto call eod at the end of the dungeon. Even if you do the values seem not right. This issue is specific to self output it does not occur on default output.

**Comment by amki** [comment]
I broke self reporting but I've fixed it in d55fa651a68ae38441242c40968690a34cb6e9bd . If you don't want to install that I hope that I can release it as a new release version tomorrow to curse forge. :)

Thank you for your report!
