### ISSUE TITLE
How to configure print end of dungeon only to party chat?

### ISSUE THREAD

**Issue by gigecogary** [amki/ElitismHelper#39]
How to configure addon to print end of dungeon only to party chat? Right now, I can only choose the channel to print it, but I dont see any option to only print end of dungeon to party chat.

**Comment by chatterchats** [comment]
> 
> 
> How to configure addon to print end of dungeon only to party chat? Right now, I can only choose the channel to print it, but I dont see any option to only print end of dungeon to party chat.

You can use the command `/eh output party`

**Comment by amki** [comment]
This was fixed, you can toggle only eod and eod to party.
