### ISSUE TITLE
Allow user to configure where output goes to

### ISSUE THREAD

**Issue by kevinpang** [amki/ElitismHelper#4]
Awesome addon, but it gets pretty spammy and pisses some people off in pugs. Still, I'd like to know for my own sake who is messing up as well as what mechanics I'm messing up. Can you add the ability to change the output to be a "print" command instead of "SendChatMessage"? That way I can configure it to only show the messages in my chat frame without bothering others with it.

**Comment by ThiefMaster** [comment]
:+1: on that, I'd like to use this in raids where I'm not lading or anything, just to see for myself who fails.

Also, some guilds might want to send this to officer chat instead of the raid chat.

**Comment by amki** [comment]
Self-reporting only has been included in 171400a89c9fa36bd0c2789e529a704c8e64a68c but you still can't configure the exact chatpane the output will go to.

**Comment by amki** [comment]
This has been added in the meantime
