### ISSUE TITLE
Updating via Curse Forge

### ISSUE THREAD

**Issue by Yihungdi** [amki/ElitismHelper#41]
There is an issue with updating from Version 0.12.3-4-g6326eb1-alpha to 0.12.4release as you can use Curse to update to
the RELEASE file but returning the next day Curse Forge is reporting that we have to update from 
Version 0.12.3-4-g6326eb1-alpha to 0.12.4release again. 
This has been on going for the last 8 days. Both files are reporting the same release date, 3/19/2021. 
Question: are both files the same with only the file name being changed from alpha to release???
Thanks for looking into this.
Like the addon, keep up the good work.

Yihungdi

**Comment by necklickhia** [comment]
Same issue, love the addon. :)

**Comment by amki** [comment]
I've pushed a new tag 0.12.5release and I hope that keeps curse from bugging out?

Can you confirm this as I stopped using curse's clients a while ago?

**Comment by Yihungdi** [comment]
AMKI,

Thanks for the update and to answer your question YES curse is now showing latest file to be 0.12.5release.

Twitch stopped doing addons about 6 months ago or more can’t remember.

Again thanks for the good work on this addon.

Yihungdi

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10
