### ISSUE TITLE
Umbral Crash in Sanguine Depths is not avoidable damage

### ISSUE THREAD

**Issue by ntowle** [amki/ElitismHelper#42]
https://www.wowhead.com/spell=334921/umbral-crash

100 yard range, it hits everyone. Standing in the graphic doesn't make you take more damage, it heals the mob (which is bad), but EH tracks everyone within 100 yards as taking avoidable damage.

**Comment by amki** [comment]
This was just fixed in 0fe835e, thank you for your report, even though I got to it very late (sorry...)
