### ISSUE TITLE
Missing abilities for Theater of Pain

### ISSUE THREAD

**Issue by Sterex0** [amki/ElitismHelper#44]
Hello,

I noticed in season one that some abilities from theater of pain are missing. Here's what I added to the spells in the lua file : 
	[330614] = 20, 		-- Vile Eruption (Rancid Gasbag)
	[321039] = 20,      -- Disgusting Burst (Disgusting Refuse and Blighted Sludge-Spewer)
	[336996] = 20,		-- Whirling Blade (Nekthara the Mangler)
	[323406] = 20,  	-- Jagged Gash (Gorechop)
In ordrer, those spells are :
- The two cones from the big abominations
- Greeen explosion from small adds (abomination wing)
- The moving and whirling blade from the first gladiator
- The hook (or bleed, I dont remember tbh) from the abomination boss, Gorechop

I tested all of them (dont hate me please healers) and they seem to be working

**Comment by amki** [comment]
Hi Sterex0,

thank you for your contribution to ElitismHelper!

I've added your changes in a7dc38a.

If you know how you could also just directly add a pull request via github.

Cheers
amki
