### ISSUE TITLE
Does this include the Tormented Lieutenant abilities?

### ISSUE THREAD

**Issue by gotex007** [amki/ElitismHelper#45]
I'm pretty sure I got hit by the Scorching Blast from Incinerator Arkolath and it didn't show or record it. Seems like an oversight to not be including the Tormented affix abilities like the Scorching Blast, Frost Lance, Cold Snap, and Massive Smash.

**Comment by amki** [comment]
Fixed in https://github.com/amki/ElitismHelper/pull/47
